[package]
name = "my_kafka_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.38"
syn = { version = "1.0.109", features = ["full"] }
my_kafka_lib = { path = "../my_kafka_lib" }
