[package]
name = "customersvc"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-service = "2.0.2"
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "8"
env_logger = "0.10"
serde_json = "1.0.138"

[[bin]]
name = "customersvc"
path = "src/main.rs"
